call contrib update gfx
call contrib update layout
call contrib update libpref
call contrib update libreg
call contrib update profile
call contrib update text
call contrib update themes
call contrib update widget
call contrib update xpcom
call contrib update xpfe
